//
//  LandingPagePresenter.swift
//  B2BMarket
//
//  Created by Firoj Shaikh on 19/08/18.
//  Copyright (c) 2018 Firoj Shaikh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LandingPagePresentationLogic
{
  func presentSomething(response: LandingPage.Something.Response)
}

class LandingPagePresenter: LandingPagePresentationLogic
{
  weak var viewController: LandingPageDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: LandingPage.Something.Response)
  {
    let viewModel = LandingPage.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
