//
//  LandingPageInteractor.swift
//  B2BMarket
//
//  Created by Firoj Shaikh on 19/08/18.
//  Copyright (c) 2018 Firoj Shaikh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LandingPageBusinessLogic
{
  func doSomething(request: LandingPage.Something.Request)
}

protocol LandingPageDataStore
{
  //var name: String { get set }
}

class LandingPageInteractor: LandingPageBusinessLogic, LandingPageDataStore
{
  var presenter: LandingPagePresentationLogic?
  var worker: LandingPageWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: LandingPage.Something.Request)
  {
    worker = LandingPageWorker()
    worker?.doSomeWork()
    
    let response = LandingPage.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
